Updates for Netlibs 3.12.0 and ROCM 6.0
iotamudelta/libflame pull request #10
Opened 2024-02-20 00:15 UTC by ItsPitt

2024-02-20 00:16 UTC, ItsPitt commented on src/base/flamec/wrappers/blas/3/hip/FLA_Trmm_external_hip.c
> +                   ( float * ) B_mat, ldim_B);
Rocm 6.0 fixes

2024-02-20 00:17 UTC, ItsPitt commented on netlib-test/create_new_testdir.sh
> +
A small charge to the script. It was erroring out after all the tests had been run and it was trying to collect the data

2024-02-20 17:25 UTC, iotamudelta requested changes
Small change to the documentation.

2024-02-20 17:25 UTC, iotamudelta commented on netlib-test/create_new_testdir.sh
> +
can you just add that into the comment in the bash script? as in "do $this b/c of $that"? Sth like "script errors out after all tests completed at data collection. Correct find path." (assuming that is correct).

2024-02-22 20:28 UTC, ItsPitt commented on netlib-test/create_new_testdir.sh
> +
Fixed in https://github.com/iotamudelta/libflame/pull/10/commits/0c0c07281e4b5c4d9f82bfe6d5fb17ab0b84f2ce

2024-02-26 18:27 UTC, iotamudelta approved these changes
LGTM

2024-02-26 18:30 UTC, merged